# pre-commit install
# pre-commit run --all-files

repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.6
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
        exclude: ^(cibuild/|tools/|third_party/|cmake/|build/|.*\.ptx\.h$)

