name: xLLM Build x86_64 ILU

on: 
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [labeled]
    paths-ignore:
      - 'cmake/**'
      - 'docs/**'
      - 'third_party/**'
      - 'tools/**'
      - '*.md'
      - '*.txt'
      - '*.yml'

env:
  JOBNAME: xllm-x86_64-ilu-cibuild-${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        github.event.label.name == 'run-ci'
      )
    runs-on: [self-hosted]
    steps:
    - name: Checkout Code
      timeout-minutes: 5
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      if: ${{ success() }}
      timeout-minutes: 60
      run: |
        chmod +x ./cibuild/build_ilu.sh
        bash cibuild/build_ilu.sh 'pip3 install pre-commit -i https://pypi.tuna.tsinghua.edu.cn/simple && python setup.py build --device ilu'
