name: xLLM Build x86_64 NPU

on: 
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [labeled]
    paths-ignore:
      - 'cmake/**'
      - 'docs/**'
      - 'third_party/**'
      - 'tools/**'
      - '*.md'
      - '*.txt'
      - '*.yml'

env:
  JOBNAME: xllm-x86_64-npu-cibuild-${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        github.event.label.name == 'run-ci'
      )
    runs-on: [self-hosted]
    steps:
    - name: Prepare submodule checkout
      run: |
        if [ -d .git/modules ]; then
          find .git/modules -type f -name '*.lock' -print -delete || true
        fi

    - name: Checkout Code
      timeout-minutes: 5
      uses: actions/checkout@v4
      with:
        clean: true
        submodules: recursive

    - name: Clean submodules
      run: git submodule foreach --recursive git clean -ffdx

    - name: Build
      if: ${{ success() }}
      timeout-minutes: 60
      run: |
        chmod +x ./cibuild/build_npu.sh
        bash cibuild/build_npu.sh 'pip install pre-commit -i https://pypi.tuna.tsinghua.edu.cn/simple; python setup.py bdist_wheel; pip install dist/* --force-reinstall; cd /tmp && python /export/home/actions-runner/_work/xllm/xllm/examples/generate.py --model="/export/home/models/Qwen2-7B-Instruct" --devices="npu:7"'
