name: xLLM Build x86_64

on: 
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'cibuild/**'
      - 'cmake/**'
      - 'docs/**'
      - 'third_party/**'
      - 'tools/**'
      - '*.md'
      - '*.txt'
      - '*.yml'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'
      - 'cibuild/**'
      - 'cmake/**'
      - 'docs/**'
      - 'third_party/**'
      - 'tools/**'
      - '*.md'
      - '*.txt'
      - '*.yml'

env:
  IMAGE: 9d0b6f5a80f6
  JOBNAME: xllm-x86_64-cibuild-${{ github.run_id }}
  VCPKG_ROOT: /export/home/vcpkg-src

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: [self-hosted]
    steps:
    - name: Checkout Code
      timeout-minutes: 5
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      if: ${{ success() }}
      timeout-minutes: 60
      run: |
        chmod +x ./cibuild/build.sh
        bash cibuild/build.sh 'pip uninstall setuptools -y; pip install setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple; pip install pre-commit -i https://pypi.tuna.tsinghua.edu.cn/simple; python setup.py build'
